<html>
    <head>
        <title>
            Blockgames
        </title>
    </head>
    <style>
        

        .block1,
        .block2,
        .block3,
        .block4,
        .block5,
        .block6,
        .block7,
        .block8,
        .block9,
        .block10,
        .block11,
        .block12,
        .block13
        

         
        {
           margin: 10px;
           width: 100px;
           height: 100px;
           border: 1px solid;
        }
      
        .block2{
            background-color: aqua;
            position: absolute;
            top: 15%;
            bottom: 8%;
            left: 4%;
        
        }
        .block3{
            background-color: yellow;
            position: relative;
            left: 40%;
        }
        .block4{
            background-color: bisque;
            position: absolute;
            left: 35%;
            top: 15%;

        }
        .block5{
            background-color: blueviolet;
            position: absolute;
            left: 35%;
            top: 32%;
        }
        .block6{
            background-color:aliceblue;
            position: absolute;
            right: 48%;
            top: 32%;
        }
        .block7{
            background-color: red;
            position :absolute;
            right: 48%;
            top: 15%;
        }
        .block8{
            background-color: green;
            position: absolute;
            right: 0%;
            top: 5%;
        }
        .block9{
            background-color: gray;
            position: absolute;
            right: 4%;
            top: 15%;
        }
        .block10{
            background-color: firebrick;
            bottom: 5%;
            position: absolute;
        }
        .block11{
            background-color: royalblue;
            position: absolute;
            bottom: 10%;
            left: 4%;

        }
        .block12{
            background-color: palegreen;
            position: absolute;
            right: 0%;
            bottom: 5%;
        }
        .block13{
            background-color: palegreen;
            position: absolute;
            right: 4%;
            bottom: 10%;
        }

        .heading{
            border: dotted 2px;
            text-align: center;
            background-color: pink;
            

        }
    
        .fotter {
    bottom: 0;
    position: fixed;
    border: 2px solid;
    text-align: center;
    width: 100%;
}


    </style>
         <body>
     <h2 class="heading">Blockgame</h2>       
    <div class="block1">block1</div>
    <div class="block2">block2</div>
    <div class="block3">block3</div>
    <div class="block4">block4</div>
    <div class="block5">block5</div>
    <div class="block6">block6</div>
    <div class="block7">block7</div>
    <div class="block8">block8</div>
    <div class="block9">block9</div>
    <div class="block10">block10</div>
    <div class="block11">block11</div>
    <div class="block12">block12</div>
    <div class="block13">block13</div>

    <div class="fotter">copyrights@2023</div>


</body>
</html>
